### ISSUE TITLE
Could not resolve placeholder 'mybatis.base.folder'

### ISSUE THREAD

**Issue by secret-superstar** [AutohomeCorp/dbtree#1]
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'mybatis.base.folder' in value "${mybatis.base.folder}"
![image](https://user-images.githubusercontent.com/54768418/72679035-51f32600-3ae6-11ea-819f-668419f9e40e.png)

**Comment by LittleShrimp1987** [comment]
sorry for not updating english readme timely. placeholder 'mybatis.base.folder' is config item for mybatis generator, if it is not required for you, you can specify any value for it.

and I have updated the document, please check that.

mybatis.base.folder
the store folder for mybatis generated code file

mybatis.mysql.connector
the location of mysql jdbc jar. you can copy dbtree/connector/mysql-connector-java-5.1.36.jar to your own folder.

mybatis.sqlserver.connector
the location of sqlserver jdbc jar. you can copy dbtree/connector/sqljdbc42.jar to your own folder
